# Generated by Django 5.0.1 on 2024-02-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('dni', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('numerosocio', models.CharField(max_length=100)),
                ('contraseña', models.CharField(max_length=100)),
            ],
        ),
    ]
